"""initial schema v3

Revision ID: 0c897f87ead5
Revises: 
Create Date: 2026-09-07 01:46:28.935668
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # referenced by JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql

revision: str = '0c897f87ead5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('rule_pipeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('seasonal_multiplier', sa.Float(), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('avg_compliance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('cross_agency_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('legal_entity_name', sa.String(length=200), nullable=True),
    sa.Column('fssai_number', sa.String(length=20), nullable=True),
    sa.Column('fssai_valid', sa.Boolean(), nullable=False),
    sa.Column('fssai_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bis_reg_number', sa.String(length=50), nullable=True),
    sa.Column('bis_valid', sa.Boolean(), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('gstin_active', sa.Boolean(), nullable=False),
    sa.Column('risk_index', sa.Float(), nullable=False),
    sa.Column('lm_violation_count', sa.Integer(), nullable=False),
    sa.Column('escalation_notes', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_agency_links'))
    )
    with op.batch_alter_table('cross_agency_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cross_agency_links_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cross_agency_links_fssai_number'), ['fssai_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cross_agency_links_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_cross_agency_links_risk_index'), ['risk_index'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('officer_id', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction_geojson', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('jurisdiction_name', sa.String(length=100), nullable=True),
    sa.Column('citizen_trust_score', sa.Float(), nullable=False),
    sa.Column('verified_reporter', sa.Boolean(), nullable=False),
    sa.Column('reports_submitted', sa.Integer(), nullable=False),
    sa.Column('reports_confirmed', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('officer','senior_officer','admin','consumer','brand')", name=op.f('ck_users_valid_role')),
    sa.CheckConstraint('citizen_trust_score >= 0 AND citizen_trust_score <= 100', name=op.f('ck_users_trust_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('officer_id', name=op.f('uq_users_officer_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('brand_pre_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_ref', sa.String(length=30), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('die_line_file_path', sa.String(length=255), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('target_pack_width_cm', sa.Float(), nullable=True),
    sa.Column('target_pack_height_cm', sa.Float(), nullable=True),
    sa.Column('target_surface_area_cm2', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('digital_badge_token', sa.String(length=100), nullable=True),
    sa.Column('badge_qr_path', sa.String(length=255), nullable=True),
    sa.Column('audit_report_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['users.id'], name=op.f('fk_brand_pre_certifications_brand_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_brand_pre_certifications_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_pre_certifications'))
    )
    with op.batch_alter_table('brand_pre_certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_pre_certifications_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_pre_certifications_cert_ref'), ['cert_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_brand_pre_certifications_digital_badge_token'), ['digital_badge_token'], unique=True)

    op.create_table('consumer_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consumer_alerts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumer_alerts'))
    )
    with op.batch_alter_table('consumer_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumer_alerts_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumer_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('price_history_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('scanned_mrp', sa.Float(), nullable=False),
    sa.Column('modal_mrp_at_scan', sa.Float(), nullable=True),
    sa.Column('scanned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('store_name', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('anomaly_reason', sa.Text(), nullable=True),
    sa.Column('overcharge_pct', sa.Float(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scanned_by_user_id'], ['users.id'], name=op.f('fk_price_history_scans_scanned_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history_scans'))
    )
    with op.batch_alter_table('price_history_scans', schema=None) as batch_op:
        batch_op.create_index('idx_price_barcode', ['barcode'], unique=False)
        batch_op.create_index('idx_price_barcode_time', ['barcode', 'scanned_at'], unique=False)
        batch_op.create_index('idx_price_store', ['store_name'], unique=False)
        batch_op.create_index('idx_price_time', ['scanned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_scans_is_anomalous'), ['is_anomalous'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_scans_scanned_by_user_id'), ['scanned_by_user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('fssai_number', sa.String(length=20), nullable=True),
    sa.Column('official_mrp', sa.Float(), nullable=True),
    sa.Column('net_quantity', sa.String(length=50), nullable=True),
    sa.Column('net_quantity_value', sa.Float(), nullable=True),
    sa.Column('net_quantity_unit', sa.String(length=10), nullable=True),
    sa.Column('country_of_origin', sa.String(length=80), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('badge_level', sa.String(length=20), nullable=True),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('last_inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_badge_level'), ['badge_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)

    op.create_table('ecom_listings_crosscheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('listing_title', sa.String(length=300), nullable=True),
    sa.Column('scraped_mrp', sa.Float(), nullable=True),
    sa.Column('physical_pack_mrp', sa.Float(), nullable=True),
    sa.Column('mrp_discrepancy', sa.Boolean(), nullable=False),
    sa.Column('country_of_origin_found', sa.Boolean(), nullable=False),
    sa.Column('online_net_qty', sa.String(length=50), nullable=True),
    sa.Column('physical_net_qty', sa.String(length=50), nullable=True),
    sa.Column('net_qty_discrepancy', sa.Boolean(), nullable=False),
    sa.Column('manufacturer_found', sa.Boolean(), nullable=False),
    sa.Column('customer_care_found', sa.Boolean(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('violation_notes', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_ecom_listings_crosscheck_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ecom_listings_crosscheck'))
    )
    with op.batch_alter_table('ecom_listings_crosscheck', schema=None) as batch_op:
        batch_op.create_index('idx_ecom_platform', ['platform_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecom_listings_crosscheck_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecom_listings_crosscheck_is_compliant'), ['is_compliant'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecom_listings_crosscheck_product_id'), ['product_id'], unique=False)

    op.create_table('inspection_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('estimated_penalty', sa.Float(), nullable=True),
    sa.Column('package_width_cm', sa.Float(), nullable=True),
    sa.Column('package_height_cm', sa.Float(), nullable=True),
    sa.Column('surface_area_cm2', sa.Float(), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('barcode_verified', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('store_name', sa.String(length=150), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('jurisdiction_status', sa.String(length=30), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('evidence_seal', sa.String(length=64), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_inspection_sessions_category_id_categories')),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], name=op.f('fk_inspection_sessions_officer_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inspection_sessions_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_sessions'))
    )
    with op.batch_alter_table('inspection_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_barcode', ['barcode'], unique=False)
        batch_op.create_index('idx_session_created', ['created_at'], unique=False)
        batch_op.create_index('idx_session_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_session_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_sessions_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_sessions_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspection_sessions_store_name'), ['store_name'], unique=False)

    op.create_table('brand_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('dispute_token', sa.String(length=100), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grounds_of_appeal', sa.Text(), nullable=True),
    sa.Column('counter_evidence_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('appellate_status', sa.String(length=30), nullable=False),
    sa.Column('appellate_officer_id', sa.Integer(), nullable=True),
    sa.Column('appellate_remarks', sa.Text(), nullable=True),
    sa.Column('hearing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appellate_officer_id'], ['users.id'], name=op.f('fk_brand_disputes_appellate_officer_id_users')),
    sa.ForeignKeyConstraint(['brand_id'], ['users.id'], name=op.f('fk_brand_disputes_brand_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_sessions.id'], name=op.f('fk_brand_disputes_session_id_inspection_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_disputes'))
    )
    with op.batch_alter_table('brand_disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_disputes_appellate_status'), ['appellate_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_disputes_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_disputes_dispute_token'), ['dispute_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_brand_disputes_session_id'), ['session_id'], unique=False)

    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_ref', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('store_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('violation_category', sa.String(length=50), nullable=True),
    sa.Column('citizen_remarks', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('claimed_mrp', sa.Float(), nullable=True),
    sa.Column('charged_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], name=op.f('fk_citizen_reports_assigned_officer_id_users')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_citizen_reports_reporter_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_sessions.id'], name=op.f('fk_citizen_reports_session_id_inspection_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen_reports'))
    )
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.create_index('idx_report_created', ['created_at'], unique=False)
        batch_op.create_index('idx_report_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_report_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_report_ref'), ['report_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_citizen_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_reports_violation_category'), ['violation_category'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('detected_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('surface_found', sa.String(length=20), nullable=True),
    sa.Column('bbox_x', sa.Integer(), nullable=True),
    sa.Column('bbox_y', sa.Integer(), nullable=True),
    sa.Column('bbox_width', sa.Integer(), nullable=True),
    sa.Column('bbox_height', sa.Integer(), nullable=True),
    sa.Column('confidence_vision_llm', sa.Float(), nullable=True),
    sa.Column('confidence_ocr_verify', sa.Float(), nullable=True),
    sa.Column('ocr_agreement', sa.Boolean(), nullable=True),
    sa.Column('ocr_read_value', sa.Text(), nullable=True),
    sa.Column('raw_pixel_crop_path', sa.String(length=255), nullable=True),
    sa.Column('font_height_mm', sa.Float(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_sessions.id'], name=op.f('fk_extracted_fields_session_id_inspection_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_fields'))
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index('idx_field_session_name', ['session_id', 'field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_session_id'), ['session_id'], unique=False)

    op.create_table('peer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=100), nullable=True),
    sa.Column('trigger_detail', sa.Text(), nullable=True),
    sa.Column('triggering_confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_peer_reviews_requested_by_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_peer_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_sessions.id'], name=op.f('fk_peer_reviews_session_id_inspection_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peer_reviews'))
    )
    with op.batch_alter_table('peer_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_reviews_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_peer_reviews_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_peer_reviews_session_id'), ['session_id'], unique=False)

    op.create_table('session_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('surface_type', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('processed_path', sa.String(length=255), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=32), nullable=True),
    sa.Column('image_width_px', sa.Integer(), nullable=True),
    sa.Column('image_height_px', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_curved_surface', sa.Boolean(), nullable=False),
    sa.Column('curvature_score', sa.Float(), nullable=True),
    sa.Column('unwarp_method', sa.String(length=30), nullable=True),
    sa.Column('transformation_matrix', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('px_per_mm', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_sessions.id'], name=op.f('fk_session_images_session_id_inspection_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_images')),
    sa.UniqueConstraint('sha256_hash', name=op.f('uq_session_images_sha256_hash'))
    )
    with op.batch_alter_table('session_images', schema=None) as batch_op:
        batch_op.create_index('idx_image_hash', ['sha256_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_images_perceptual_hash'), ['perceptual_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_images_session_id'), ['session_id'], unique=False)

    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('legal_clause', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_crop_path', sa.String(length=255), nullable=True),
    sa.Column('calculated_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('discrepancy', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('penalty_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_sessions.id'], name=op.f('fk_violations_session_id_inspection_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_violations'))
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index('idx_violation_clause', ['legal_clause'], unique=False)
        batch_op.create_index('idx_violation_rule', ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_status'))
        batch_op.drop_index(batch_op.f('ix_violations_session_id'))
        batch_op.drop_index('idx_violation_rule')
        batch_op.drop_index('idx_violation_clause')

    op.drop_table('violations')
    with op.batch_alter_table('session_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_images_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_images_perceptual_hash'))
        batch_op.drop_index('idx_image_hash')

    op.drop_table('session_images')
    with op.batch_alter_table('peer_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_reviews_session_id'))
        batch_op.drop_index(batch_op.f('ix_peer_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_peer_reviews_review_status'))

    op.drop_table('peer_reviews')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_session_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_name'))
        batch_op.drop_index('idx_field_session_name')

    op.drop_table('extracted_fields')
    with op.batch_alter_table('citizen_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_reports_violation_category'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_session_id'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_citizen_reports_report_ref'))
        batch_op.drop_index('idx_report_status')
        batch_op.drop_index('idx_report_geo')
        batch_op.drop_index('idx_report_created')

    op.drop_table('citizen_reports')
    with op.batch_alter_table('brand_disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_disputes_session_id'))
        batch_op.drop_index(batch_op.f('ix_brand_disputes_dispute_token'))
        batch_op.drop_index(batch_op.f('ix_brand_disputes_brand_id'))
        batch_op.drop_index(batch_op.f('ix_brand_disputes_appellate_status'))

    op.drop_table('brand_disputes')
    with op.batch_alter_table('inspection_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_sessions_store_name'))
        batch_op.drop_index(batch_op.f('ix_inspection_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_sessions_officer_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_sessions_brand_name'))
        batch_op.drop_index('idx_session_status')
        batch_op.drop_index('idx_session_geo')
        batch_op.drop_index('idx_session_created')
        batch_op.drop_index('idx_session_barcode')

    op.drop_table('inspection_sessions')
    with op.batch_alter_table('ecom_listings_crosscheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecom_listings_crosscheck_product_id'))
        batch_op.drop_index(batch_op.f('ix_ecom_listings_crosscheck_is_compliant'))
        batch_op.drop_index(batch_op.f('ix_ecom_listings_crosscheck_barcode'))
        batch_op.drop_index('idx_ecom_platform')

    op.drop_table('ecom_listings_crosscheck')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand_name'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_index(batch_op.f('ix_products_badge_level'))

    op.drop_table('products')
    with op.batch_alter_table('price_history_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_scans_scanned_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_scans_is_anomalous'))
        batch_op.drop_index('idx_price_time')
        batch_op.drop_index('idx_price_store')
        batch_op.drop_index('idx_price_barcode_time')
        batch_op.drop_index('idx_price_barcode')

    op.drop_table('price_history_scans')
    with op.batch_alter_table('consumer_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumer_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_consumer_alerts_barcode'))
        batch_op.drop_index('idx_alert_user_read')

    op.drop_table('consumer_alerts')
    with op.batch_alter_table('brand_pre_certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_pre_certifications_digital_badge_token'))
        batch_op.drop_index(batch_op.f('ix_brand_pre_certifications_cert_ref'))
        batch_op.drop_index(batch_op.f('ix_brand_pre_certifications_brand_id'))

    op.drop_table('brand_pre_certifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_brand_name'))

    op.drop_table('users')
    with op.batch_alter_table('cross_agency_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cross_agency_links_risk_index'))
        batch_op.drop_index(batch_op.f('ix_cross_agency_links_gstin'))
        batch_op.drop_index(batch_op.f('ix_cross_agency_links_fssai_number'))
        batch_op.drop_index(batch_op.f('ix_cross_agency_links_brand_name'))

    op.drop_table('cross_agency_links')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_sector'))

    op.drop_table('categories')
    # ### end Alembic commands ###
